### PR TITLE
Add byte-range column and enhance type display for len-delim fields

### PR DESCRIPTION
**Pull request by mayfield**
Hi,  I use your utility all the time for reverse engineering.  It's great.  I had a couple enhancements I wanted for my own use, but you might find them beneficial.   So here is a PR.

### CODE REVIEW

**Comment by pawitp** [comment]
Thank you for the contribution!

**Comment by pawitp** [comment]
Oh, seems like I didn't setup the pipeline to run tests for PRs. Can you help make another PR to fix existing tests and test the new byte decoding behavior?

**Comment by mayfield** [comment]
> Oh, seems like I didn't setup the pipeline to run tests for PRs. Can you help make another PR to fix existing tests and test the new byte decoding behavior?

Sure thing, having a look now.

**Comment by mayfield** [comment]
While I'm there would you be okay with me using your pretty hex for the binary output from my first commit?  Might as well be consistent in how hex is represented.

**Comment by pawitp** [comment]
> While I'm there would you be okay with me using your pretty hex for the binary output from my first commit?

Please feel free to include that change.

**Pull request merged**
