### PR TITLE
Fix 'Each child in a list should have a unique "key" prop'

### PR DESCRIPTION
**Pull request by aronmal**
Console output:
`Warning: Each child in a list should have a unique "key" prop.`

### CODE REVIEW

**Review by pawitp — CHANGES_REQUESTED** [review]
Using a UUID is not a good solution because the UUID changes every render which does not help React re-use elements. See https://reactjs.org/docs/reconciliation.html#:~:text=predictable%2C%20and%20unique.-,Unstable%20keys,-(like%20those%20produced

A better way is to just use the array index as the key.

**Comment by aronmal** [comment]
OK, I agree with you. But I am not having iterating indexes all the time. I am currently working on a migration tool for Google Authenticator TOTP codes form `otpauth-migration://offline?data=...` to `otpauth://totp/...` format for [2FAuth](https://github.com/Bubka/2FAuth) and when I export/transfer 4 accounts at a time, I get one QR code with the first scheme, I extract the `offline?data=...` part, decode it from [URL encoding](https://en.wikipedia.org/wiki/Percent-encoding), than i have a base64 string, which I put in your tool and got the owner and issuer, and the secret, but as plain text instead of base32. So what I did this weekend was reverse engineering your code to better understand protobuf. Problem seems to be, it is a lot of bit calculation and shifting. So [our plan](https://github.com/Bubka/2FAuth/issues/74) was to either to implement a variant of your code in the vue frontend or make a npm package out of it to convert the Google Authenticator 'otpauth-migration://' format. - If your ok with that.

The protobuf decoded part looks somewhat like this:
```
[
  {
    "index": 1,"type": 2,"value": [
      {  "index": 1,"type": 2,"value": "secret_value"},
      { "index": 2,"type": 2,"value": "owner_value"},
      { "index": 3,"type": 2,"value": "issuer_value"},
      { "index": 4,"type": 0,"value": "value"},
      { "index": 5,"type": 0,"value": "value"},
      {"index": 6,"type": 0,"value": "value"}
    ]
  },
  {
    "index": 1,
    "type": 2,
    "value": [
      {  "index": 1,"type": 2,"value": "secret_value"},
      { "index": 2,"type": 2,"value": "owner_value"},
      { "index": 3,"type": 2,"value": "issuer_value"},
      { "index": 4,"type": 0,"value": "value"},
      { "index": 5,"type": 0,"value": "value"},
      {"index": 6,"type": 0,"value": "value"}
    ]
  },
  {
    "index": 1,
    "type": 2,
    "value": [
      {  "index": 1,"type": 2,"value": "secret_value"},
      { "index": 2,"type": 2,"value": "owner_value"},
      { "index": 3,"type": 2,"value": "issuer_value"},
      { "index": 4,"type": 0,"value": "value"},
      { "index": 5,"type": 0,"value": "value"},
      {"index": 6,"type": 0,"value": "value"}
    ]
  },
  {
    "index": 1,
    "type": 2,
    "value": [
      {  "index": 1,"type": 2,"value": "secret_value"},
      { "index": 2,"type": 2,"value": "owner_value"},
      { "index": 3,"type": 2,"value": "issuer_value"},
      { "index": 4,"type": 0,"value": "value"},
      { "index": 5,"type": 0,"value": "value"},
      {"index": 6,"type": 0,"value": "value"}
    ]
  },
  {
    "index": 2,
    "type": 0,
    "value": "value"
  },
  {
    "index": 3,
    "type": 0,
    "value": "value"
  },
  {
    "index": 4,
    "type": 0,
    "value": "value"
  },
  {
    "index": 5,
    "type": 0,
    "value": "value"
  }
]
```

**Comment by pawitp** [comment]
You can get the iterating index from the second parameter of the function passed to `.map`. See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map.

Your use-case is a bit off-topic for this discussion. I would strongly suggest not using this project (or a variant) but instead use the [proto file](https://github.com/digitalduke/otpauth-migration-decoder/blob/master/src/otpauth-migration.proto) for the format with a "proper" Protobuf library for NodeJS. I cannot recommend which one to use because I have not used any of them before.

**Comment by aronmal** [comment]
Oh well, I could have thought of that too :sweat_smile:! Hope your happy now :stuck_out_tongue_winking_eye:

**Review by pawitp — APPROVED** [review]
LGTM. Thank you for your contribution!

**Pull request merged**
