### PR TITLE
GH Actions

### PR DESCRIPTION
**Pull request by konsumer**
Related to #88 

This adds 2 actions for publishing to Github Pages (I think that needs some config in Settings) and Testing directly in Github Actions. 

This improves speed and issue-visibility.

You can see example job-runs:
- [pages](https://github.com/konsumer/protobuf-decoder/actions/runs/8904456934)
- [test](https://github.com/konsumer/protobuf-decoder/actions/runs/8904456933/job/24453756467)

And since I have `konsumer.js.org` hooked up to my github pages, it creates [this](https://konsumer.js.org/protobuf-decoder/)

It also drops CircleCI, since that is not really needed (Github Actions would take over that job.)

### CODE REVIEW

**Comment by konsumer** [comment]
Currently, I didn't have any coverage-gating, but that could be added as part of test job. I think also `static` could depend on `test`, which would merge the 2 `npm ci` calls, and not allow a site-publish with failing tests.

Coverage, as it is, might be a bit tricky, because we'd need to grab previous coverage, and compare it on test, but I find these kinds of automated tests a bit annoying, especially on frontend projects (with limited react-level testing) so I think it's fine without it, personally.

**Comment by konsumer** [comment]
I think I may have added back all the coverage stuff without circleci, in last commit. It seems to hang on ` curl https://codecov.io/bash` but that might be because I haven't set it up for my fork.'

It shows nicely in the action-run, though:
Screenshot 2024-04-30 at 8 22 13 PM

**Comment by konsumer** [comment]
I added a github secret for `CODECOV_TOKEN` and now it shows up:

Screenshot 2024-04-30 at 8 28 40 PM

So, I think that is all that is needed.

**Comment by konsumer** [comment]
I'd also like to get rid of these warnings, but it might just be a problem with semantic-ui-react. Have you ever used [daisyui](https://daisyui.com/)? It's a similar UI toolkit, but uses tailwind and produces smaller output (much less CSS and no JS) and has some really nice theming options. I use this a lot for my own projects.

Screenshot 2024-04-30 at 8 35 51 PM

**Comment by pawitp** [comment]
Hi. While I appreciate the contribution, I'm not looking to migrate any CI/hosting pipeline at the moment. Particularly, what exists right now works fine and the netlify domain performs decently well on SEO.

**Pull request closed without merging**
